### ISSUE TITLE
WIP Potential To Do List!

### ISSUE THREAD

**Issue by KMFDManic** [KMFDManic/mame2003-xtreme#32]
@grant2258 , @arcadez2003 , @gpstar81 , @markwkidd

First of all, thank you to all 4 of you for helping make this so incredibly awesome!

Ok, going over some things that I had not added yet.  I will try to test things and see how they work out.

- Tetris Grand Master Speed Fixes (should work well with Xtreme)
- Mortal Kombat Hacks (Who would have thought these would cause RPI Scene Drama!)
- Light Gun Accuracy Fixes (If these help with general Mouse/Controller Movements, Yes!)
- Rewind Fix (I mainly need to verify this doesn't break Robotron 2084's insane rewind glitch!)

This Issue is mainly so you guys can see what I am going to most focus on.  As always, you are welcome to suggest anything, too!  But, definitely already so much to work with, so I will find no shortage of things to add, to keep Xtreme into the 2020s for awhile:)  Thanks, as always!

And, hope all is well with you @gpstar81  !  I truly hope you are staying safe, since I hadn't heard from you for a hot minute!

**Comment by arcadez2003** [comment]
BTW i reverted Tetris Grand Master II Speed Fixes, as it cost me 40fps on the xbox, i assume the
cost will be similar on some of the lower spec hardware your core is aimed at.

**Comment by arcadez2003** [comment]
You should consider the PGM update from a little while back which would net you the following.........

New games

DoDonPachi Dai-Ou-Jou
DoDonPachi Dai-Ou-Jou (Black Label)
ESPGaluda
Ketsui: Kizuna Jigoku Tachi
Oriental Legend Special
Photo Y2K / Real And Fake
Puzzle Star
The Killing Blade

Games now with sound

Knights Of Valour / Sangoku Senki
Knights of Valour Plus / Sangoku Senki Plus
Oriental Legend / Xi Yo Gi Shi Re Zuang

Added the ICS2115 soundcore for the PGM games
Updated the PGM driver to MAME105 more games are now playable
Added support for the Cave PGM games and improved the ICS2115 soundcore thanks to ShmupMAME and amadvance for the code

**Comment by KMFDManic** [comment]
@arcadez2003 Excellent suggestion:)  I remember having fun testing out those commits with Plus.  Thanks!

**Comment by arcadez2003** [comment]
@KMFDManic  Here ya go im stuck in the house as per the rest of the UK, so rounded up all the PGM stuff you will require drop these into your core and they should be good to go........

https://www.sendspace.com/file/skipfb

Any compile problems just lemmie know.

**Comment by KMFDManic** [comment]
@arcadez2003 My entire area is in lockdown, as well.  But, my jobs are considered essential, so I am still working during the scary time.  What I find craziest is how many people are out and about, that really do not need to be!  It is almost like a horror movie, as I am seeing human behavior truly taking on changes you'd never quite expect.  You finding anything to occupy your time?  Movies, TV, Music, Gaming?  

And, thanks so very much for the PGM Assist!  I greatly appreciate anything like that that stands out.  PGM is always exceptionally awesome.  Come to think of it, there were a few other PGM games that really stood out, that I found mainly worked with later MAME/FBA, but not all too well on lower spec hardware, such as Demon Front, The Gladiator.  And, backport wise, a team of ex-SNK devs worked on this great brawler, which mainly runs with MAME 2010 and on...Crystal of Kings.  I was super happy with other games that you backported in the past, such as Night Slashers, the "True Strider" spiritual sequel Cannon Dancer, Boogie Wings, etc.  I know it is pretty hit or miss exactly what can or cannot be backported, especially something like OutFoxies "Sound", etc.  AdvanceMAME was able to pull off OutFoxies "Sound", I believe.  But, it is a different code base

I will get the PGM addition added, tested, and showcase it.  I am also working in a few other things for other Cores, such as Genesis Plus GX and Fceumm and P-UAE.  MAME will always be my lifeblood, my number one, along with NES, though!  You have a favorite system?  Me, NES/Arcade, then MD, SNES, etc, with CD Based Systems probably being lower on the spectrum, for me, comparatively speaking to cartridge based ones.  Thanks again!

**Comment by KMFDManic** [comment]
@arcadez2003 Errors I got compiling:

In file included from src/drivers/pgm.c:222:0:
src/drivers/pgm.c: In function ‘construct_pgm’:
src/driver.h:257:36: error: ‘SOUND_ICS2115’ undeclared (first use in this function); did you mean ‘SOUND_TMS5110’?
  machine_add_sound(machine, (tag), SOUND_##type, &(interface));  \

src/drivers/pgm.c: In function ‘construct_cavepgm’:
src/driver.h:257:36: error: ‘SOUND_ICS2115’ undeclared (first use in this function); did you mean ‘SOUND_TMS5110’?
  machine_add_sound(machine, (tag), SOUND_##type, &(interface));  \

src/drivers/pgm.c: In function ‘construct_killbld’:
src/driver.h:257:36: error: ‘SOUND_ICS2115’ undeclared (first use in this function); did you mean ‘SOUND_TMS5110’?
  machine_add_sound(machine, (tag), SOUND_##type, &(interface));  \
                                    ^

Makefile:548: recipe for target 'src/drivers/pgm.o' failed
make: *** [src/drivers/pgm.o] Error 1

**Comment by ghost** [comment]
I just tested it its working fine here. If your using windows i know what the issue might extract the zip first then copy from the extracted folder. It didnt work for me the first time i just dragged the files from a list(had to reboot to unlock them only experienced this behaviour in windows though notepad++ used to do it to me all the time has been fixed since.

**Comment by arcadez2003** [comment]
> 
> 
> @arcadez2003 Errors I got compiling:
> 
> In file included from src/drivers/pgm.c:222:0:
> src/drivers/pgm.c: In function ‘construct_pgm’:
> src/driver.h:257:36: error: ‘SOUND_ICS2115’ undeclared (first use in this function); did you mean ‘SOUND_TMS5110’?
> machine_add_sound(machine, (tag), SOUND_##type, &(interface)); \
> 
> src/drivers/pgm.c: In function ‘construct_cavepgm’:
> src/driver.h:257:36: error: ‘SOUND_ICS2115’ undeclared (first use in this function); did you mean ‘SOUND_TMS5110’?
> machine_add_sound(machine, (tag), SOUND_##type, &(interface)); \
> 
> src/drivers/pgm.c: In function ‘construct_killbld’:
> src/driver.h:257:36: error: ‘SOUND_ICS2115’ undeclared (first use in this function); did you mean ‘SOUND_TMS5110’?
> machine_add_sound(machine, (tag), SOUND_##type, &(interface));
> ^
> 
> Makefile:548: recipe for target 'src/drivers/pgm.o' failed
> make: *** [src/drivers/pgm.o] Error 1

I forgot to declare the soundcore in makefile.common i'll send you the file shortly which should
sort the compile errors, im going back over the original PGM commits to make sure i didn't miss
something else.

**Comment by arcadez2003** [comment]
@KMFDManic Here is the updated makefile.common it should get rid of the compile errors.

[makefile pgm.zip](https://github.com/KMFDManic/mame2003-xtreme/files/4438573/makefile.pgm.zip)

**Comment by ghost** [comment]
worked for me with the one i downloaded pull req is in form your original file check the pull req compiled fine for me never done a clean compile to be fair.

edit: I see what you mean now must have been because the .o file was there from changing branches

**Comment by arcadez2003** [comment]
> @arcadez2003 My entire area is in lockdown, as well. But, my jobs are considered essential, so I am still working during the scary time. What I find craziest is how many people are out and about, that really do not need to be! It is almost like a horror movie, as I am seeing human behavior truly taking on changes you'd never quite expect. You finding anything to occupy your time? Movies, TV, Music, Gaming?

Oh trying to keep myself occupied best i can im playing Captain Toad Treasure Tracker just now
i bought season 9 of The Walking Dead real cheap, i just got a new book part two of the Jim Ross
trilogy " for those not in the know JR was and is the best play by play man in the Wrestling history"

AEW Dynamite is still on every week but it's not the same without the crowd, apart from that
just going the odd walk or two when the weather is good slip on the headphones and fire up
Absolute radio.

They'll lift the lockdown in a month or so as they're losing too much money for it to  continue 
much longer.

**Comment by arcadez2003** [comment]
> 
> 
> worked for me with the one i downloaded pull req is in form your original file check the pull req compiled fine for me never done a clean compile to be fair

Thanks bigman i forgot to dec the soundcore in the makefile the new one i sent in the above post
should sort it, always a mystery as to why one core will build it and another craps out on compile
with exactly the very same code.

**Comment by KMFDManic** [comment]
@arcadez2003 @grant2258 Yeah, very goofy how sometimes it will work fine for one platform, and not for another.  In any case, Updated, and this is the current error.  

make: *** No rule to make target 'src/machine/pgmy2ks.o', needed by 'mame2003_libretro.so'.  Stop.

Almost there:)

**Comment by ghost** [comment]
im doing a clean compile at the moment  do this in the mean time. 

git checkout master
git fetch origin
git pull
make clean 
make -j8

if that doesnt work do a 
git checkout master
git reset --hard origin/master
make clean
make -j8

**Comment by KMFDManic** [comment]
@grant2258 No luck, yet.  Will try again shortly.

**Comment by ghost** [comment]
yea same i notice when you run make its deleting the file for some reason. Forgot t mention the pull request is in.

**Comment by arcadez2003** [comment]
Could just add the file manually right enough.

**Comment by ghost** [comment]
I did try that after i copied it over and typed make it disappeared. I loaded linux up it done the same thing. I ended up using root changing permissions the the files didnt dissapear. Think something wennt wrong the git hub end alls well that ends well. Things are dire here fed up with the house at least the cats entertaining!

**Comment by arcadez2003** [comment]
Aye it feels like the end of the world is nigh, i guess all this PGM porting will be for nothing ha ha.

**Comment by ghost** [comment]
hahah least youve naw lost your humour

**Comment by KMFDManic** [comment]
@arcadez2003 @grant2258 Maybe, there was an issue with Github?  I tried recompiling after grabbing source again, and it worked.  I tried it 3 times earlier, with a failure each time.  Gonna test it now, to verify it works!

**Comment by KMFDManic** [comment]
Even though it compiles now, it doesn't appear that the PGM commits have taken.  Hopefully, whichever conflict exists is an easy one to resolve.  I, of course, also retested the same games and BIOS along with Plus, all functioning.  Thanks, both of you, for trying to help get this addition added!

And, yeah, hopefully, the lockdowns won't continue "indefinitely".

**Comment by ghost** [comment]
source files were in the root directory as well pull request is in and is tested works here locally. I a little gutted no Demon Front love that wee game! @KMFDManic  hopefully we will have some normality soon

**Comment by arcadez2003** [comment]
@grant2258 Aye nice game i like it, unfortunately MAME78 doesn't have the ARM7 CPU that 
most later PGM games use as a protection device, but there is always hope that an unprotected version might turn up one day.

BTW That's how we can support Oriental Legend Special in this core, a few years back there was
gaming tournament in china and PGM sent an unprotected version of that game so it could be
played at the event, it then as things tend to go went missing and was later dumped.

So since we only need to emulate the M68k and Z80 CPU's and not the protection ARM7
that game now works in this core if a similar unprotected set ever turned up for Demon Front 
it would be easy to support it here.

**Comment by KMFDManic** [comment]
@arcadez2003 Thanks so much for the background on the PGM stuff.  Everything is working great now!  And, thank you @grant2258 !  I will get a video up.  I was also playing around with doing some variations to handle Xtreme Slowdown with NES/MD Games, and such, on those respective Cores.  I will do some showcasing of that, too.  Contra Force, for NES, for example...is near unplayable on the actual hardware!  But, with emulation, it plays near flawlessly!

**Comment by ghost** [comment]
@KMFDManic  it was arcade work copied i never done anything extra apart from making the mistake of copying the files in the root folder instead of the src directory I spotted it in the end though duh. I also got  the chance to watch upgrade.

@arcadez2003 Ill check how much is involved in for the arm7 since its only for this one thing is needed for the first release should be good to go. Well if mr kd is interested in having demon front on his port. I can place it on my todo at some point list.

**Comment by arcadez2003** [comment]
@grant2258 Aye i actually backported the ARM7 CPU to MAME84 a couple of years ago i took
it from MAME94 then backported Ryan Holtz thumbnail support for it from MAME113, you'd
then have to add the CPU and game support to the driver.

KOV2 which was my tester was 60fps until you started a game then the ARM7 kicks in sending 
game commands back and forward and it dropped to 5fps, you'd get the very same speed more
or less in this core with the platforms it's aimed at.

Reading up on Demon Front further the sim is only for the internal/external romcheck i think i
assumed wrongly it only uses the ARM7 for that, like KOV2 and the rest of the PGM games
which use that CPU it'll likely require data sent back and forth and that is what slows em down.

But hey if your using your barcade core on your PC then you should have no troubles the game
does have a speedup and you can easily update the driver making sure to use code from a 
version of MAME which still has the ARM7 speedups.

BTW if you were to take on this insane challenge mind and add The Gladiator Road OF The Sword
you'll thank yourself for it later as it's the best game on the system ;)

**Comment by arcadez2003** [comment]
@grant2258 we're both stuck in the hoose if you get board we could tag-team up and go for
the gold the last bit of code i have which at the moment cant be rolled back to MAME78.........

http://adb.arcadeitalia.net/lista_mame.php?game_sourcefile=seibuspi.cpp&arcade_only=0&current_version=0

They'd work a treat speedwise on any of the old cores are great shmups but we are missing the
I386 CPU, im confident should it be packported we'd have the games up and running in no time
or was that famous last words :)

**Comment by ghost** [comment]
would i pie handle a i386 at good speeds you recon?

**Comment by arcadez2003** [comment]
Well the one from MAME84 will be quite fast and faster i would think in the older MAME78 core
with these games they tend to be full speed on the xbox, but they do throw around some heavy
duty graphical effects especially the sequels which slowdown here and there, Raiden Fighters
and Viper Phase 1 are more or less full speed all the time though.

I've noticed with some of the heavy duty games already backported to the older core they're
faster on the Rpi than the xbox so im thinking speed wont be an issue here, one thing i've
noticed is the single board versions of the games tend to be faster and the chinese 2000
versions faster still.

Fuck i forgot you guys have advanceMAME Rpi ports those should play these games already
so you'll be able to try em out and get a feel for how they might perform, but that then begs
the question since you already have em there might be no need to actually attempt to backport
em to MAME2003 Xtreme and they'd likely struggle on some of the system kd aims this core
at anyhow.

**Comment by ghost** [comment]
These systems are running arm like the pie should compare well with the xbox to be honest. I dont think the classics run a full os maybe KMFDManic can let us know. Im not sure if advanced mame will run on it. I dont mind doing a wee project but like you said there needs to be a good reason beyond boredom!

**Comment by arcadez2003** [comment]
There ya go that's two things i've talked us out of ha ha, i might as well try and tackle the newer
Data East protection in later MAME, as it would fix Fighters History from messing up on the last
boss fight, you take on two bosses at once and the prot sim cant keep up when they fire off
their special attacks both at the same time.

Some of the code is highly incompatible though so i might bend your ears for some advice should
i need some help, i would look to add it as a new machine file and just hook it up to that one game
as the rest of the Data East prot sims are good enough for the other games and it'll save a ton of
testing.

**Comment by ghost** [comment]
well if i get the motivation ill add them two cpu cores weather or not they are used the updates go beyond just mame2003 anyone any port thats using the 78 code base can use them. Like yourself I dont really use these older cores its just a hobby thing.

Ive nearly reached my hobby goal on my build of 2003 that is using a barcade with gamespads and it all works. Ive redone everything to how i wanted to do it and it nearly ready to go and ive nearly reached my person pinacle no one will see it right enough unless the compile it off chance but you know how it is just pass some time.

**Comment by arcadez2003** [comment]
Well if you were to backport the I386 i'll defo use it to try and get the Seibuspi games up and
running, with regards to the ARM7 again if you needed any assistance getting Demon Front to
work then i'll be around.

**Comment by KMFDManic** [comment]
@arcadez2003 @grant2258 Video of PGM in action on MAME 2003 Xtreme:)  Very very very pleased and happy with the results!  Killing Blade is quite an interesting one!

https://www.youtube.com/watch?v=-YsP17V1MCc

Demon Front, if it ever worked, would be a pretty mindblowing entry, considering!  Thanks for all you both have done to help out!  Truly means a hell of a lot!

**Comment by ghost** [comment]
@KMFDManic nice video mate dont know how you find the time !

**Comment by arcadez2003** [comment]
@KMFDManic Glad to see the PGM update worked out and you get decent performance in those
games, it's a combination of three things really, the faster ole core, the faster pgm video code, and 
i kept the faster timers in the sound core a triple whammy if you will.

Couple of times you've mentioned The Crystal Of Kings, like with Demon Front we're missing the
CPU required in order to run the game, it wasn't added until MAME90, on the xbox core someone
backported it and the game works but performance wise we only get 5fps on that one.

So whoever it was that added support for it kinda wasted their time, you'd only get the same kinda performance with the game in this core so for these reasons it's a nonstarter really.

**Comment by KMFDManic** [comment]
@arcadez2003 @grant2258 Yep, everything is working fantastic!  Thank you both.  I have been busy working.  I will try to finish up a few more Cores, then get things posted for others to enjoy on the Mini Classics.  I will try getting more stuff added into MAME 2003 Xtreme, once I post this Update.  PGM was an excellent suggestion, for sure.

I am also checking out some of the shows/movies you guys recommended.  Walking Dead, I am definitely a little behind, now!  How is the show holding up most recently?  I will probably play catch up!

**Comment by arcadez2003** [comment]
Isn't it lovely looking..........

https://www.youtube.com/watch?v=PoOJ8uc0CAE

**Comment by ghost** [comment]
loads of freely available media packs  for front ends like that these days. Biggest problem is some people are trying to selling em when setting it all up for folk. 

I personally just use the old fashion type of snapshots of a game. I find videos annoying and tacky personally. I guess that shows my age though lol.

**Comment by KMFDManic** [comment]
@arcadez2003 That had actually been a fairly common request, having a "video attract" mode style.  It definitely looks quite slick and nice!  I am happy with the ability to display Box Art+In Game Shots, with our current enough implementation.

@grant2258 If I change anything else, it might be a minor touch-up to which Core Options are enabled/disabled, such as making sure Cheats are always enabled, etc.  Other than that, after this Update, I may try to get some of those Sports Hunting Games in, as well as the Golf ones.

Things are getting a little less crazy in my area, with supplies such as Toilet Paper, Towels, etc, actually finally being available, to a degree.

I saw a movie pop up called Corona Zombies, which showed a Zombie wearing a mask, and hoarding Purehell Sanitizer, Toilet Paper, Paper Towels.  With most companies not doing much in the way of movie productions, right now, I kind of figured something was up with the movie.  It is merely a redubbed, kind of "Mystery Science Theater" style affair, of 2 B Movies.  

One movie I really did like fairly recently, was Upgrade.  If you at all like Sci-Fi/Horror, you both might like it.

**Comment by arcadez2003** [comment]
> 
> 
> loads of freely available media packs for front ends like that these days. Biggest problem is some people are trying to selling em when setting it all up for folk.

Yeah your always gonna get that im afraid as some people are just too lazy to set everything up
and want things ready to go outta the box so to speak with all the media and rom files present 
and are willing to pay someone to do it for em.

Like yourself i know alotta the Coinops dev team and media creators hate the fact someone might
come along and make money off the back of their work, but when something is in the public domain what can ya do to stop it.
> 
> I personally just use the old fashion type of snapshots of a game. I find videos annoying and tacky personally. I guess that shows my age though lol.

Same here :) although it was more of a space issue with my Xbox HDD, screenshots take up
less space than video files, and then when i had a bigger HDD i could not be assed rounding
up all the media packs so just stuck with my snaps instead.

**Comment by arcadez2003** [comment]
Seta2 for the hunting games and Itech32 for the golf games, i might round up the code for ya
later today as well im stuck in anyway it'll give me something to pass the time.

**Comment by ghost** [comment]
@KMFDManic  I actually did get round to watching upgrade and i was not expecting that ending was a decent movie. The cheats are implemented in your core already. Some games will put in different controls with cheats activated like bzone and others just keep that in mind. There might be an issue on your port with paths for the cheat file though would need to look at the code as make changed the code in plus to allow high score saving while cheating ect so its all different. 

@arcadez2003  being bored i think ill plug my dusty old xbox360 out havent used it in years have two of them with glitch chips installed. 
I think it was auroa i installed on it back then. Is there a data file and a place i can get the latest download the latest MAMEoXtras. I just finished a session of leisure suit larry yesterday. I think auroa can be updated just dont wanna mess with it too much as it works lol. 
edit: 
@KMFDManic tested the cheats and the option it does work however you need to restart the core so mame initializes it. the cheat file needs places in systemdir\mame2003-xtreme\cheat.dat. There is also a mcr3 nvram fix here is that's something your interested in as well.

**Comment by ghost** [comment]
@KMFDManic ive been looking at your source at some point someone removed the fir filter from mame2003 and plus for some reason. I personally think this makes games sound better ill recored samples with it on and off you can decide if its something you would like at add a core option for it or not all your doing is setting a variable. 
[filter.zip](https://github.com/KMFDManic/mame2003-xtreme/files/4492993/filter.zip)

**Comment by arcadez2003** [comment]
> 
> @arcadez2003 being bored i think ill plug my dusty old xbox360 out havent used it in years have two of them with glitch chips installed.
> I think it was auroa i installed on it back then. Is there a data file and a place i can get the latest download the latest MAMEoXtras. I just finished a session of leisure suit larry yesterday. I think auroa can be updated just dont wanna mess with it too much as it works lol.

https://www.emuxtras.net/forum/viewtopic.php?f=183&t=6855&sid=3d2dae55c5ed6bdedae6132c010d10d9

**Comment by arcadez2003** [comment]
@KMFDManic https://www.sendspace.com/file/906p0n

With regards to the golf games you might need to tweak the analog settings for the trackball
speed and sensitivity a little as i did have some trouble striking a good balance with these ones 

As too much sensitivity means the ball travels too far and too fast, but not enough means the 
opposite trial and error will get the job done, getting it correct for shorter shots on or close to
the green caused me the most trouble.

Also of note is unlike the other games in this driver we have no speedups for these games but i found they all performed well enough on the xbox so it should be same in this core.

**Comment by KMFDManic** [comment]
@arcadez2003 Excellent.  I am working tonight.  But, I will grab and compile and test after work:)  I have one good friend who is absolutely in love with Golf Games.  So, he would be awesome in helping test the sensitivity.  And, aside from Walking Dead, any other "Zombie" fare you are into or have been into?  I am generally into horror, to begin with.  Cabin in the Woods was a fun horror flick from several years back.  And, of course, like all the Evil Deads, even the remake wasn't half bad.  

@gingerbeardman Hope all is well!  And, if you are up to helping test, we can sign off on a final value which might work well for these Golf Games that are gonna be added to MAME 2003 Xtreme!

@grant2258 If you don't mind a "crazy" movie, check out Brawl in Cell Block 99.  It starts like your typical drama, then becomes absolutely and incredulously insane once things get rolling.  Those that watched the movie with me couldn't watch the screen with how utterly violent it became in some parts!  You will have to see for yourself!

**Comment by arcadez2003** [comment]
@KMFDManic I like the survival/horror genre so i suppose if you can think of any movie of that
type i'll likely have seen it :) anyway you could do alot worse than checking out........

https://www.youtube.com/watch?v=aqkqF--v1tg

**Comment by KMFDManic** [comment]
@arcadez2003 I'll throw together a list of some I liked.  One new survival movie called The Hunt.  It was campy but entertaining.  Survival movies for me started with the 1970s Warriors.  Add horror to them, even better.  The Collector/Collection.  Combine martial arts, horror, and survival, even more so better.  I rewatched all 3 Blade movies.  I really liked Raid and Raid 2 Redemption, too, for over the top martial arts.

**Comment by ghost** [comment]
I recommend ip man 4 as far as kung fu goes. https://www.youtube.com/watch?v=jGwzfl7oouw it is dubbed in English all of em are. I would recommend them all if you havent seen them. Ip man is the guy that trained mr lee for what its worth.

**Comment by KMFDManic** [comment]
@arcadez2003 @grant2258 Thanks again!  I officially posted the Update, and people have really been enjoying things!  I will try to work in the Golf/Hunting Games Next Update.  It won't be as big an Update as this one, obviously!  MAME is a beautiful thing, indeed!

I did start Ip Man 4, roughly 30 minutes, so far.  I will finish it on your recommendation, @grant2258 

I also enjoy horror, and started watching The Platform on Netflix.  And, also checking out a few other shows, such as Trailer Park Boys, Derry Girls, Still Game, and so on.  I really really need to catch up on Walking Dead!  The last season I watched was at least 2-3 back!  I watched every single episode up til that point!  I just ended up getting occupied with a few other things, such as work, modding, etc!  But, now I know what show to catch up on!  So, thanks @arcadez2003 

Both of you feel free to suggest anything else!  And, for the hell of it, I posted Release at (if you wanna see the comments of people checking it out.  You both are incredible.  And, very glad to have such amazing friends as you at my side!  Stay Safe!

https://www.reddit.com/r/RockinTheClassics/comments/g9777k/lets_go_all_xtreme_mode_activate_with_some_mame/

AND

https://www.reddit.com/r/PlaystationClassic/comments/g977ih/lets_go_all_xtreme_mode_activate_with_some_mame/

Will close this topic, for now.  Feel free to respond, obviously!  But, anything else for Next Update, and on, I will just start a new Topic:)  

Will try to find out where I left off in Walking Dead, now!

**Comment by arcadez2003** [comment]
Well feel free to check out the changelog to see what you might like for this core.......

https://github.com/libretro/mame2003-plus-libretro/blob/master/CHANGELOG.md

Some will require more graft than others no pain no gain :), but you should defo look at doin this one sometime as you'll net some good sound fixes for the Sega System 18 games...........

reverted the RC5c68 soundcore back to the superior earlier version pre the MAME76 changes

**Comment by arcadez2003** [comment]
BTW we should talk about the Midway Y and T-Unit games sometime, you have the DCS speedups
for MK2 and the Midway W-Unit games, but you dont have the Williams speedups in this core
nor does MAME2003-Plus have em.

Certainly the performance you get across the platforms this core is aimed at with regards to 
Mortal Kombat, Narc and NBA Jam will determine if you want to explore this further or not ;)
