### ISSUE TITLE
Altered Beast/Hang On Sega Fix-Ups

### ISSUE THREAD

**Issue by KMFDManic** [KMFDManic/mame2003-xtreme#4]
@arcadez2003 How has it been?  I am glad that you stuck around in the Scene, as you have done so much for MAME, which is by far...the entire reason I got into Emulation to begin with!  I would greatly appreciate it if you could take a look at Altered Beast (glitchy and unplayble) and Hang On (missing graphics), which I recall you fixing for Plus, last year.  Xtreme and Plus are the two go to Cores for the Mini Classics and their lower spec hardware.  It would be amazing if you could give a little insight into these two, specifically.  I am very happy with the current status of the Core.  But, Sega definitely needs a little touching up!  Thank You, in advance:)

P.S.  Again, I have seen much of the drama that you have been involved with, and I am just glad you came out on top!  Many will never realize just how much you actually have done for them, when they are playing their many many amazing Arcade games, heh:)  I was following the "latest thread" on MAME 2003 Plus, and was so close to stepping in, as I really have appreciated all you and Grant2258 have done over the last couple years.  Grant may be stubborn.  I, myself, am quite stubborn..at times!  But, I really did like him and got along great with him in all of our communications.

**Comment by arcadez2003** [comment]
Hey @KMFDManic how's it hanging :) @grant2258 fixed Altered Beast by updating the m68k
CPU maybe he'll chime in around which commits you should look to port across, i think it's
this one..........

https://github.com/libretro/mame2003-plus-libretro/commit/28a4a59b44c2fb6039503c3d9b1733936c50c809#diff-50f8a42fd909f503d60d49e1ee028286

We also updated the whole Sega core for many graphical and sound improvements for the System 16 / 18 based games this also includes the changes that get Hang-On to work.............

Big Sega Core Update
https://github.com/libretro/mame2003-plus-libretro/commit/28a4a59b44c2fb6039503c3d9b1733936c50c809

Sound fix for Sega 18 games

https://github.com/libretro/mame2003-plus-libretro/commit/a8f3e9815d6f41de2d0f24f5cb39a138587adb84#diff-96a65ea3e9e2eb15444823ea75dc337c

If you dont wanna tackle the big core update then @grant2258 M68000 CPU changes
and the Rf5c68 sound fixes are what you need, and i can point you towards the commits that
fix Hang-on which came before we updated the core so you can just drop em in here.

Regards!!

**Comment by arcadez2003** [comment]
Hang-On changes pre the big core update the code will drop in here easy enough.......

sharrier.c
https://github.com/libretro/mame2003-plus-libretro/commit/5d1dbf8830ae7c90ec04ca839e4a2e272bdeeed7#diff-50f8a42fd909f503d60d49e1ee028286

system16_vidhrdw.c
https://github.com/libretro/mame2003-plus-libretro/commit/c29c1d212afb18089b76bae5bd7a224c083f055f#diff-ca95edd001c4ed270320dbb47488b644

**Comment by ghost** [comment]
hi there just finished a shift its just the 68k cpu update you need for altered beast. The newer 68k is a little slower so i can patch the old one if you prefer it easy enough to do. 

Thanks for the kind words mr kd. It the libretro drama effect what happened im over it. There is no real lasting effects of this for me. Ive always got on with yourself and arcadez.

**Comment by arcadez2003** [comment]
Aye i've had drama for nigh on six years, firstly xbox scene sillyness and lately libretro, but no
matter im over it now water off a ducks back, @grant2258 i take it this is the fix for Altered Beast..........

https://github.com/amadvance/advancemame/commit/103a2f2c22470110af8c835f06e780c6eccc4f4d

I never bothered porting it to the xbox as that platform seemed to be unaffected by it

**Comment by ghost** [comment]
think it was only later versions of  gcc not sure is that the exact fix for our version but it is only two operands that need fixes as far as i can remember.

found the issue where i fixed it 

https://github.com/libretro/mame2003-libretro/issues/176#issuecomment-374816643

just make sure generate the new files as the libretro port wont update this itself

**Comment by KMFDManic** [comment]
@grant2258 Very glad to still be able to keep in touch with you.  I will touch base with you both about anything related to this stuff, when I am off from work tomorrow.

@arcadez2003 I greatly appreciate you lending your expertise, as between you and grant, lower spec hardware setups actually have a chance of enjoying many Arcade games that would normally only run on MAME 2010 and on!  I actually was playing one specific game, the other day...got it in my video..in fact!  The 3D Gradius, AKA Solar Assault.  MAME 2014 can load the parent rom, which has an eeprom issue.  The clones, however, which don't appear to be supported til later MAME variants, do work!  It is a really cool game.  Kinda wonder if that would be possible in MAME 2003 Plus!  3D Gradius, hell yeah:)

35:35 minute point, to see what I am clarifying about, as well as the gameplay.  

https://www.youtube.com/watch?v=g9gG1kN-CZM

I shall follow-up with you both when I get a free chance to.  But, hope you both get a kick out of 3D Gradius AKA Solar Assault!

**Comment by arcadez2003** [comment]
I was never able to get a kick outta G-Darius as like all the PSX 3D arcade games they ran like
a dog on the xbox, all the lower spec platforms that use MAME2003 will highly likely run it
the same way, put it this way some of em struggle to run Virtua Fighter and that's fine on
the xbox so the performance on some systems is less even than an xbox console.

Not straightforward either as no doubt the PSX CPU will require some changes and that's before
we'd have to roll back the zn driver + add the protection and hookup the sound, and it i think
it would all be for nothing when you factor in the performance we'd get in these 3D games.

**Comment by ghost** [comment]
the only psx 3d game i have a soft spot for is xevious loved it.

**Comment by KMFDManic** [comment]
@grant2258 You may have noticed that I had covered Xevious in this same video, hehe:)  Thanks for the fix on Altered Beast!  I am not as concerned with Hang On, for now.  Plus is the perfect companion piece, in that respect!  

@arcadez2003 I am mostly curious on Solar Assault, since it runs on the typically harder to compile MAME or MAME 2016 Cores.  I would hope it to run better than the znc PS1 style games.  I am pretty sure that even in my video, ones of that driver run pretty bad.  Solar Assault ran quite a deal better, considering.  I am not too worried about it.  It was just a thought, since I had looked into it, a bit.  I am sure you have looked at a ton of games that could potentially be back ported, in any case!

**Comment by KMFDManic** [comment]
@grant2258 Also, just to confirm...I will do very limited Updating to the Xtreme Variant.  Main thing is having a good mixup between MAME 2003 Plus and Xtreme.  For the Mini Classics, I may stick to posting primarily Plus and Xtreme, as they both cover about all you can do for MAME 2003.  Other very quick notes...

Somehow, not sure why, but the Midway Merge that we did awhile back isn't appearing to be working with the Midway games, as in they are not automatically changing to 22050 bit rate.  Maybe, you can take a quick look at that?  And, the other merge request, which I was unsure whether or not I should do, the controller mapping changes, The Mini Classics come with an NES controller, SNES controller, and a PS1 WITHOUT Analog controller.  How do you think these would work out if I did commit that change.  I just don't wanna overcomplicate things for those on simpler controllers.  I, myself, use a Wii controller..so, I never have issues.

**Comment by ghost** [comment]
Well the classic input mappings are just vanilla mame settings if your ok with things as they are just leave it. Ill have a look at the midway games when I get some time. I havent looked at the mame source for a while will need to navigate it again.

was this ever fixed for you or did you just set the sample rate to 22050 to fix it? I cant see any commits in the history for this on your branch. I can add it if it hasnt been added.

**Comment by KMFDManic** [comment]
@grant2258 yep, I realize now that I was running with backup overrides for 22050  I am glad things can run without the training wheels now!:)

**Comment by arcadez2003** [comment]
Nothing on the tele so i've ported across the fixes which get Hang-On playable

**Comment by KMFDManic** [comment]
@grant2258 @arcadez2003 Everything is testing out great.  As far as things will be, moving forward, Xtreme is helpful on RetroPie 2, Mini NESC/SNESC/PSC, for the more stubborn games, being that they are generally lower spec hardwares.  MAME 2003 Plus and Xtreme are perfect companion pieces to one another.  Macross 2 is a really cool SHMUP, as well.  The commits are working for both of the Cores.  So much better with the music that doesn't try to start, fade out, and stop, repeatedly:)  And, Grant, I suggested, jokingly to gpstar, about Airwolf with the real TV theme, eh:)  Thanks again, guys!  I will get a demonstration video or few up over the next few days.  I also found a great SHMUP for the Amiga, with an incredible Soundtrack, that will make it into my video, too:)  Definitely not your every day shooter.

**Comment by ghost** [comment]
Glad all is working out well. I do seem to remember a conversation about airwolf the real them would be so much better sounds awesome. I loved that show when I was young many years ago!

I love your port all the warning screens are still there when there is issues with the drivers. I must admit i havent plugged my ole pie in for a while might just do a little  barcade port build for myself if i get bored at some point. I use this mini pc now with mame stand alone and big box. Still peope who dont have that hardware should still have a nice experience.

**Comment by arcadez2003** [comment]
Ok been looking over the core all seems well with regards to code ported across from MAME2003 + although i noticed you didn't have the fixes to make Power Instinct Legends actually work so i've added em for ya, plus for good measure i've also included the changes to the CPU comms so the background characters will now do their thing in Power Instinct 2 and Legends.

Also sent a fix for

https://github.com/libretro/mame2003-plus-libretro/issues/548

Might as well fix this next..........

https://github.com/libretro/mame2003-plus-libretro/issues/577

**Comment by ghost** [comment]
thndzone was a damn good game i never played it until that fix well worth the effort. arcade ill have to branched on my repo master and https://github.com/grant2258/mame2003-plus-libretro/tree/lrmame2003-plus any fixes i do will come from the latter. 

The master branch is just little things im changing for my own build. All ive done so far is restored the warnings so  i know when there is a working clone ect.

**Comment by arcadez2003** [comment]
Agreed great wee game, as i said i've been checking out this core it seems mostly to stick with
the original MAME2003 sources but with a splattering of MAME2003+ code, in light of that
i've been looking at some wee fixes and improvements for some of the bigger name games
we've done which wont require any rom changes in keeping with the direction of this build.

Also just quick and easy stuff as i dont wanna get to bogged down with heavy duty porting
at the moment ;)

**Comment by ghost** [comment]
haha i know the feeling just making my port easy simple set the controls up. Disable the none legacy stuff that doesnt work well hide it for now.

**Comment by KMFDManic** [comment]
@arcadez2003 That is the gist of what I am going for, here.  Legacy MAME 2003 Coding, with a sprinkling of what would most benefit us on the lower spec hardwares.  Plus and Xtreme go hand in hand as perfect companion pieces to one another.  The biggest thing for me is any other potential backporting that could be done, of other games.  I am pretty sure you've been through the whole gamut of those, by now.  But, every game matters, especially the fixed up Macross 2, which is great:)  It is a shame Outfoxies isn't an option, along with a few other games we have briefly gone over in the past.  But, Night Slashers most certainly makes up for that:)

@grant2258 I kind of wonder how well Airwolf would hold up in a rewatch, nowadays!  Some shows are still fun to watch, many years later, such as Knight Rider.  Others, like the original 60's Batman, you gotta wonder..."What the hell was I thinking, ever watching this to begin with:)"

**Comment by ghost** [comment]
Well that is true but compare it to what else was out then and its still great for its time. I kinda feel the same about movies these days (most not all)  its a one watch thing TV shows are a lot better than movies these days. I guess there is only so much you can get in 3 hours max though. America i have to admit has the art of TV shows mastered thr guff we get in the uk is shocking lol.

**Comment by KMFDManic** [comment]
@grant2258 I agree that many current movies aren't watchable a second time.  But, I really enjoyed "Upgrade":)  That is easily worth a 2nd watch.

**Comment by KMFDManic** [comment]
@arcadez2003 Everything great, just had to fix up Hang On, due to a compilation error myself and another mate ran into, in test compiling.  All good now:)  And, I got a demonstration of Macross 2 up in my video.  You both rock, and I thank you very much:)

10:33 in, for Macross 2  You might enjoy this, as well @grant2258 

https://www.youtube.com/watch?v=fHpL6e9r7yo&feature=youtu.be

**Comment by arcadez2003** [comment]
Aye i forgot about the commit i added after the original Hang-On update which sorted the above
silly me :D 

Staying on Sega i see you've still got the RF5C68 sound core from MAME78 this is actually bad
and should be rolled back to a previous version which will improve the sound in some system 16
and all system 18 and 32 games.

**Comment by ghost** [comment]
@KMFDManic  Always like the ole videos mate but there was two important things missing a cat or cats and at least one keyboard. Joking aside its nice to give users a perspective to whats involved in it all well done on that matey. I take it you cross compiling from a x64 or x86 machine?
 
@arcadez2003 watch you dont go down that rabbit hole hehe

**Comment by arcadez2003** [comment]
Ha ha nae chance of that im on a classic Nintendo trip just now, which is taking up the time i
used to put aside for dev work, just started Metroid Zero Mission never played that one 
before and im lovin it so far.

**Comment by ghost** [comment]
im em-barest to say i was playing sf2 earlier and guile(spelling) beat me twice with ryu that should never happen lol. I am enjoying using emus more as well since i stopped doing dev stuff. Did you try the unreleased wonderland dizzy for the nes its not too bad if you like the dizzy games mate. I love tge yolk folk what can I say.  

All im doing atm is fixing 2003+ how i want it to work in my barcade. I have the notifications fixed the old mame osd messages are back.  Basically simplifying it and use it like you would stand alone. Itll probably take me forever the pace i go at these days

**Comment by KMFDManic** [comment]
@grant2258 Need a human opponent for Street Fighter 2:)  And, yes Cross Compiling from Ubuntu, like in my last video:)  

@arcadez2003 Everything is absolutely wonderful, right now.  I will see if I can think of a few more things I might want to add.  I MAY want to have Metal Slug 5 going with Xtreme, too.  I think the rebase to Plus at the time is why that got lost in transition.  1-4 and X work fine.  5 didn't last I tested.  May need to retest, just to be certain.  But, 5 loaded fine with Plus.  Otherwise, even the Crazy Balloon game is interesting...Like playing Operation:)  Thanks for the additions..!

**Comment by arcadez2003** [comment]
@grant2258 fixed up Metal Slug 5 so it worked in plus, the code should be easy enough to port
across to Xtreme.

**Comment by ghost** [comment]
IF you have any problem sorting it let me know my weeks holiday from work is over back to work tonight if you done get any joy let me know ill have a look at the weekend when im off.

**Comment by arcadez2003** [comment]
Im more or less done, the driver and machine are sorted just need to update the video code
slightly to drop in the recent graphical improvements and the speedups.

@KMFDManic just a heads up some of the roms will need to change we did this for two reasons
to fix the games so they will work while others were changed for ease of availability.

**Comment by arcadez2003** [comment]
Ok here's the neogeo update.......

https://www.sendspace.com/file/qt3p76

King Of Fighters 2003, Metal Slug 5, Samurai Showdown 5, and Samurai Showdown 5 Special
should now work, and i've also added the recent video improvements and the speedups

**Comment by KMFDManic** [comment]
Thanks @arcadez2003 , things should be perfect for my next Release, along with the great stuff you guys have done with Plus.  along with some of the awesome stuff @arnoldsecret had also added for Plus.  Love the very classic game additions:)

As far as the nifty 1942 hack he had brought up...One thing I always wondered was why RetroArch had not implemented something similarly minded to the fast forward/slow motion/rewind feature...a global turbo fire feature.  The Turbo Fire works great with Cores like Turbografx-16/CD Mednafen PCE-Fast (But, that was native to the controller on the system, to begin with!).  Still, it would be a damned beautiful thing, indeed to incorporate a Core Option for Turbo Fire with variable rate changes.  Imagine how much better SHMUPS would become!  

Speaking of "Tele" @arcadez2003 , I just finished up "The Boys" on Amazon Prime..It was a pretty interesting superhero show.  I also got in season 1 of Jack Ryan, and watched Sneaky Pete.  in the UK, I liked the show Inside No. 9  I had always been a fan of stuff like Twilight Zone, Outer Limits, etc.  Black Mirror on Netflix is the most current thing closest to this.  But, Inside No. 9 is pretty cool, too.  Not sure what you usually watch!

And, @grant2258  I very much believe that the movie Blue Thunder, from 1983, is the inspiration for Airwolf, which came out in 1984.  Blue Thunder is one of those movies I kept passing by when I was a kid.  But, I almost wanna watch it now, and see how it holds up.  I think it is easy to watch, for free, too...on stuff like Crackle.  Hell, who knows, sometimes movies like that are on YouTube, too, heh.

**Comment by meowthed** [comment]
this reminds me, I gotta work on adding the 5 new hacks to plus, it's just that college gets in the way.

**Comment by KMFDManic** [comment]
@arcadez2003 this error turns up when attempting to cross compile, via the latest commits:

src/driver.h:517:2: error: 'init_svcchaos' undeclared here (not in a function); did you mean 'initsvcboot'?
  init##INIT,       \
  ^~~~~

Any input before I try to fix anything up?

**Comment by arcadez2003** [comment]
Yeah the INIT for svcchaos must have got lost in the shuffle i'll add it back in now :)

**Comment by KMFDManic** [comment]
@arcadez2003 thanks for going out of your way on this one.  I look absolutely forward to promoting some of your recent additions with Plus, too.  I should be posting the next Mini Update after the weekend.  I did some touching up with another mate, for ScummVM, as well.

All Metal Slugs in Plus and Xtreme is MAME in top peak form:)

**Comment by KMFDManic** [comment]
@arcadez2003 @grant2258 @arnoldsecret Everything is in tip top shape now, and I will get another demonstration video or two up over the next few days.  I will be primarily focused on the combination of usage with Plus/Xtreme, to give the best overall stability, compatibility, performance, speed...for anyone on these lower spec hardware platforms I work with!  I still think it would be a fun venture to look into being the first Arcade Core/s to implement a Turbo Fire feature!  The 1942 hack definitely makes a fun case of this concept in action!  Not to mention, Turbo Fire, at an average rate of 16 times per second, absolutely makes games like Final Fight a riot!  We implemented Turbo Fire, another way, via bash scripts.  But, I would love to see this directly embedded within the coding of said Cores.  Here is a video demonstration of me utilizing Turbo Fire:)

3:10 in for Final Fight Arcade (Note: running the Custom OST with this, as well:)

https://www.youtube.com/watch?v=fvlvlZ4Nozs

As a final note, anything any of you 3 feel might benefit as an Xtreme addition, I am very much open to!  I love both Cores, and will continue to Update Xtreme, as well as keep Plus as optimal as possible with my feedback and personalized testing...Macross 2 worked out very nicely!  Thanks again, all of you:)
