### ISSUE TITLE
Unsafe OC Vs Scale Clock Implementation!

### ISSUE THREAD

**Issue by KMFDManic** [KMFDManic/mame2003-xtreme#46]
Thanks @grant2258! (Null and Void For now:)

Thanks!!!

**Comment by ghost** [comment]
I would need to trace cpu init not sure I'd a reset calls it if it does you can do it. I think for the cpu clock speeds just put what you want in the driver just leave remarks with the original speed in case you ever need to revert. All the changes are unstable so unpredictable. I would need to test it to see if can be tweeted on the fly

**Comment by KMFDManic** [comment]
@grant2258 thanks:)  Let me know how things turn out.  I can finetune things, rename for better clarity, etc, once it is coded in.  The individual drivers (KI, etc), I can just handle as I need to, since they might be too messy to try to work in as Core Options.  But, the cpuexec  (the primary final goal for this overall project)  should cover the gist of all else I need for the low spec environment.

Other than that, I think I'll be pretty good on what I wanted done.  Even the CPU1-5 is not as important in the grand scheme of things! As always, a true debt of gratitude:)  Looking forward to any test feedback on your end.  I suspect we may need to "restart" after each concurrent cpu change.  But, we will know soon enough!  

And, by the way, how is the night shift job going for you?

**Comment by ghost** [comment]
unfortunately I dont see any easy way to do this atm will keep on looking though. The problem is the cpu does an init for timers  ect i tried changing the clock speed and reset that didnt work unfortunately. Ill keep on digging when I get more time. Youll need to hard code the drivers for now . Im not sure what you mean by cpuexec in assuming you mean changing the clock speed on the fly.

I was working during the pandemic just got made redundant jobs going not too bad. Im doing a leadership role dont really like it to be honest prefare to be more hands on.

**Comment by KMFDManic** [comment]
@grant2258 Don't go too crazy trying to pinpoint what will make it stick.  I already appreciate the effort you put into trying, as it stands!  I will close this issue, for now.  But, thanks!  I can do things another way, if need be.  It just will need to remain hard coded.  

And, yeah, hands on is also a little better when it comes to how long days seem, at work!  I've done combination of management as well as the standard fare.  It is a little harder to take "telling people" what to do, rather than being hands on, and helping out.  I was never one of those types that just sit in the office all day, playing on the computer or a phone.  I try to be out with the other workers, working, too.  It isn't as if we have to do paperwork for hours on end, or anything!  The guy who was management where my wife worked, ONLY sat in the office all day...He never did anything.  So, literally, all the workers who were getting screwed over by his behavior, just upped and walked out!  So, he ended up having no choice but to actually do something.  Last time I popped into that place, that manager was on a register!  Previous to that, he refused to help any employees do anything, ever!  Karma:)
