### ISSUE TITLE
Let's add Michael Jordan to NBA Jam!:)

### ISSUE THREAD

**Issue by KMFDManic** [KMFDManic/mame2003-xtreme#50]
@arcadez2003 @mahoneyt944 @Zoltan45 @MistyDreams

Hello all.  I have been occupied with work and reality related fun stuff over the last month.  But, I am back and hoping to help make more waves with 2003 Xtreme/Plus, one of the very best outlets for those with lower spec AND higher spec hardwares!

It is a travesty that Michael Jordan was never in the original NBA Jam, due to a clause in his contract with Nike, at the time!  Assets exist within NBA Jam, however, that may point to him originally being a very strong consideration.  So, let's fix this!!!  Not only that, aside from Jordan, this would also allow Shaquille O'Neal, (following were removed in later revisions) playable cheerleaders, Raiden, Scorpion, Sub-Zero, Reptile, backboard smashing, cussing, etc, hacks:)

**Showcase of Jordan at around 4:00**

https://www.youtube.com/watch?v=vhwE29KzVe8&list=PLoymeELwTrDXXiMbnHqFTZrJzTcTNBsgn&index=1

**Zolton45, who did previous work with NBA Jam, got this going on his Repo!:)**

https://github.com/Zoltan45/mame-mkp/commit/f8196f5e3a9b987d6366d22019bcb00ee491c06b

My only qualm is possibly renaming the roms to be more concise with general naming conventions, rather than having:

l1_nba_jam_tournament_game_rom_ug14.ug14, a naming convention that is more precise, to keep things better aligned, moving forward!

Works great in Xtreme, by the way.  But, want a proper addition, with "your" combined expertise, so issues aren't abound!:)

![IMG_20221218_220746](https://user-images.githubusercontent.com/25908399/208323971-59e3f06c-b390-467e-80ef-bdd9356468d5.jpg)
![IMG_20221218_220815](https://user-images.githubusercontent.com/25908399/208323973-e49db81b-c822-4510-8bb0-a2549c146335.jpg)

Let me know if any of you need additional information, files to test, etc!  I would love to have this as a practical addition for both Plus-Xtreme!!!

**Comment by KMFDManic** [comment]
**My demonstration of it running on 2003 Xtreme:)!**

https://www.youtube.com/watch?v=RtFSP62i3PI

**Comment by mahoneyt944** [comment]
Looks interesting. So just need to correct rom naming?

**Comment by KMFDManic** [comment]
@mahoneyt944 yeah, I think it would be a bit more practical to handle naming in a more concise manner typical of mame naming, at your discretion.  Once we get this done, and accounted for in 2003 xtreme and plus, I can have DemiGodX also update his patch to reflect our final take. It is definitely pretty badass being able to play as MK characters, Shaq, Jordan, etc.

**Comment by Zoltan45** [comment]
I would definitely change some rom names for those which are unique to this game.  I shoehorned the game into my mame build, but I did not revisit to rename the roms or do any cleanup as of yet.  IE l2.1_nba_jam_tournament_game_rom_uj12.uj12 -> nbajamter.uj12 or nba_jam_tournament_rewind_game_rom.uj12 and so one for every rom that is patched for this hack.

**Comment by mahoneyt944** [comment]
Modified roms using `nbajamtr.uj12` naming scheme would be fine. Any roms that are not modified should use the original parent naming though.

**Comment by mahoneyt944** [comment]
There's actually another issue with mame2003. nbajamte is under nbajam, which in later mame nbajamte is its own parent. That probably needs fixed too

**Comment by mahoneyt944** [comment]
Names are 8 characters so it should be nbajamtr

**Comment by MistyDreams** [comment]
Im not a gig baseball person but if I was its a worthy addition

**Comment by KMFDManic** [comment]
I suggested to DemiGodX to make Urkel aka Jaleel White, a potential unlockable character, in a future revision.  Who else is as iconic from the 1980s-1990s, as far as TV personnas:)

**Comment by Zoltan45** [comment]
> Names are 8 characters so it should be nbajamtr

where is this limitation placed?  I just looked through my fairly recent full romset and there are several romzips that are longer than 8 characters.  just curious really.

**Comment by Zoltan45** [comment]
> I suggested to DemiGodX to make Urkel aka Jaleel White, a potential unlockable character, in a future revision. Who else is as iconic from the 1980s-1990s, as far as TV personnas:)

would be great if he could post tutorials or tools, if he hasnt already.  He never approves my comments on his announcement video so I am not sure how active he is on youtube.  Would be great to polish up bart simpson and godzilla since the player models and I think the heads and callouts are available.  Not sure if that was this game or another version.

**Comment by mahoneyt944** [comment]
> > Names are 8 characters so it should be nbajamtr
> 
> where is this limitation placed? I just looked through my fairly recent full romset and there are several romzips that are longer than 8 characters. just curious really.

Some probably deviate from that but that's what it's suppose to be. That's why revs of TE are t2, t3, etc instead of te2, te3. I recall there being some overflow issues with the cheat engine too since it expects this standard, at least the cheat engine in 2003. It's noted so here. But haven't followed the logic to confirm.
https://github.com/libretro/mame2003-plus-libretro/blob/d7579d7c3c7658059fb6584b32e0b29aa30f1fd8/src/cheat.c#L212

**Comment by mahoneyt944** [comment]
there's also differences in mame2003 to current mame with rom naming and rom loading. So if trying to shape this into mame2003, its going to look different. Without changing all the rom loading and naming conventions, it would look like this i believe. UNTESTED.
https://github.com/libretro/mame2003-plus-libretro/pull/1501/files

**Comment by KMFDManic** [comment]
@mahoneyt944 seems sound and fitting, commit wise.  I will give it a test when I'm able to.  I'm also gonna try to update some cheats for that hack.  You're good on test files, on your end?

**Comment by mahoneyt944** [comment]
i dont have the hack to test. just whipped the PR together

**Comment by KMFDManic** [comment]
@mahoneyt944 Just dropping this til you confirm you grabbed it.  Obviously, you will need to rename the roms based on your new commits:)

https://drive.google.com/drive/folders/1KlV1y0wZwgCA0acw_WXWN92mXnUMQb0N

Let me know once you grab 'em:)

**Comment by mahoneyt944** [comment]
Got it

**Comment by mahoneyt944** [comment]
@KMFDManic this commit adds it, this is the "get the bleep outta here" version btw, no need to rename the actual files they load by the checksum.
https://github.com/libretro/mame2003-plus-libretro/commit/b6019e68677b13253b2af054feb81e30bc54f830

**Comment by KMFDManic** [comment]
@mahoneyt944 beautiful:) Let me know how it plays for you.

**Comment by mahoneyt944** [comment]
Seems to play pretty well, played as scorpion and Raiden, heard the "get that bleep outta here". I'm not overly familiar with the game but it seems to run properly. One note to the rom hacker, the checksums need updated for the on board test, while not necessary, it's helpful when they are to ensure patching is done correctly.
![nbajamtr-221219-202930](https://user-images.githubusercontent.com/49591133/208563915-bde2f16e-6aa3-489f-a296-2cd8aea7676f.png)

**Comment by KMFDManic** [comment]
@mahoneyt944 great.  There are a lot of cool things you can do in the game, such as unlock special hidden characters by typing in their initials, and so on.  I'll try to get together some notes on this stuff, as it truly adds to the game.  I will try to get updated cheat codes for this patched version added as well.   Thanks again:) 

And, u can do interesting fatalities, such as set opponents on fire, too.  You first have to do a cheat code to enable them, then I believe you score 3 times in a row to be on fire, then all hell breaks loose, haha:)

**Comment by Zoltan45** [comment]
what is the difference between mame2003extreme and mame2003plus?  Also, does everyone live in Ohio? :)

Also another kind of aside tidbit that I would like to see carried over stateside.  When I started looking into older mames I found out that in Asian countries at least, they update their old emulators to the current mame romset names and checksums.  So that you can drop your, lets say, NBA Jam rom from mame .250 into the roms directory for this project and it would just work.

Has anyone been able to communicate with Demigodx and tried to get him into this discussion?

**Comment by KMFDManic** [comment]
@Zoltan45 2003 Xtreme was my personal decision to take in a less stable direction than Plus. Both originated from 2003 Upstream code set.  So, it isn't as recommended for purists.  It was also where we first tested Custom CD Soundtracks for 2003, before Plus added them, and so on. Plus is the better build for public consumption.  Xtreme is for those who are on platforms, such as the Mini Classics, which dont run Cores quite as well as RetroPie, etc.  Several from the Plus Team and FBNEO, etc, have been gracious, kind, and truly helpful and instrumental in helping me fulfill what I envisioned MAME wise:)

I'm in Ohio, US. I don't think anyone else from here is.

**Comment by Zoltan45** [comment]
I am in Cleveland Ohio :)

**Comment by mahoneyt944** [comment]
> they update their old emulators to the current mame romset names and checksums

This is technically possible but requires constant maintenance with very little gain for most titles. This is why we typically update roms as needed, as in if they offer a fix for a known issue or something. Plus mame2003 loads roms not only by name but by checksum, so even if the name doesn't match if you have the correct file it will still load.

**Comment by KMFDManic** [comment]
I work just a few minutes out of the West Side of Cleveland.  

As far as checksums, yes, that is one thing that has proven to be very nice with 2003 Plus/Xtreme, especially when it comes to merging rom sets and bioses.

**Comment by Zoltan45** [comment]
> I work just a few minutes out of the West Side of Cleveland.  
> 
> 
> 
> As far as checksums, yes, that is one thing that has proven to be very nice with 2003 Plus/Xtreme, especially when it comes to merging rom sets and bioses.

Yeah I love the versatility with this emulator for most users.

I don't think it would be that hard to maintain. Converting the emulator would be an absolute nightmare though.  If I were to personally do it, I would probably figure some way to eliminate  multitudes of clones, which of course violates the spirit of mame and possibly the license.  It takes some dedication for those that maintain the older mame versions overseas. They have some wild variants too.

I live in old Brooklyn and work in middleburg heights.

**Comment by KMFDManic** [comment]
@Zoltan45 Many clones, bootlegs, etc., have practical purpose.  You may encounter censorship in one version that isn't in another, such as green blood versus red blood.  For the longest time, bootlegs of some sega games, like Moonwalker, E-Swat, Choplifter, were more reliable in earlier MAMEs than the real dumps. Of course, hacks can also be useful, such as being able to use 8 directions for shooting in Ikari Warriors instead of forced rotary tank controls.

**Comment by Zoltan45** [comment]
> @Zoltan45 Many clones, bootlegs, etc., have practical purpose. You may encounter censorship in one version that isn't in another, such as green blood versus red blood. For the longest time, bootlegs of some sega games, like Moonwalker, E-Swat, Choplifter, were more reliable in earlier MAMEs than the real dumps. Of course, hacks can also be useful, such as being able to use 8 directions for shooting in Ikari Warriors instead of forced rotary tank controls.

Exactly.  Most of the time I am dealing with current mame as well and you can build that any way you please.  Basically you can prune it very much to your preferences, with some very wordy make commands.
