### ISSUE TITLE
Hard Drivin' Force Brake

### ISSUE THREAD

**Issue by KMFDManic** [KMFDManic/mame2003-xtreme#53]
Null Issue:)

**Comment by mahoneyt944** [comment]
I recall getting past the calibration before, no idea what I did exactly... But I have the nv file that's gets to the game. I recall not implementing it because the controls just don't translate well imo. I think to make this game playable, it needs a shifter hack implemented or fake shifter inputs.
[harddriv.zip](https://github.com/KMFDManic/mame2003-xtreme/files/14028544/harddriv.zip)

**Comment by KMFDManic** [comment]
@mahoneyt944 I will test out your nvram, as well.  That is what I found strange.  I had zero issues doing the calibration for Plus.  But, no registering of input for the brake on Xtreme.  Hard Drivin' controls, if you've ever played the Arcade Version for real, were hideously bad.  So, you gotta definitely keep that in mind:)  I'd still love to incorporate some sort of bootstrap for this, if I can pull a decent enough one off.  Thanks:)

**Comment by KMFDManic** [comment]
@mahoneyt944 Ok, testing your nvram pretty much pointed to where the issue was.  With Xtreme, the "shifter" seems to need mapped, in order to be able to use "gas", even in automatic.  Very strange.  But, you did a great job with that particular nvram:)  I now have good controls.  Thanks:)

**Comment by KMFDManic** [comment]
@mahoneyt944 

[harddriv.zip](https://github.com/KMFDManic/mame2003-xtreme/files/14106113/harddriv.zip)

I was able to get a good nvram in my testing.  If you aren't otherwise too busy, check the one I dropped out, and let me know if it is any better for you than the one you generated.  I have it where you can hold R1 to accelerate and drive shifter is auto selected.  Thanks again for the bootstrap assist.  I was able to successfully do the ones I wanted to do, and will start incorporating them into Xtreme.  Viable ones, I will pull request to Plus:)

**Comment by mahoneyt944** [comment]
That seems to help for automatic mode, but I'm unable to shift in manual mode. This games just not for me.....to play this game properly you need a dedicated setup or implement complete hacked controls imo.

**Comment by mahoneyt944** [comment]
The sega genesis has a good port of this game, interestingly neutral in this port becomes drive for automatic mode. that might be a viable hack for mame. https://youtu.be/pcAYJk1OYaw?si=heV8_lYSIFPfLLf6

**Comment by KMFDManic** [comment]
@mahoneyt944 automatic good.  I will do another one to try to properly implement manual mode.  Thanks for testing.  I think we can pull this off.  And, yeah, love the MD version!

**Comment by KMFDManic** [comment]
@mahoneyt944 Will take a little getting playing around to try to get the "manual" transmission set up feasibly.  Will see what I can do on it.  Hard Drivin' Genesis/MD, I grew up with and always loved that one.  If you are at all a Hard Drivin' fan, you gotta try Race Drivin' a Go! Go! for PS1, Japan

**Race Drivin' a Go! Go!**

https://www.youtube.com/watch?v=sVib1W_wI2U

My primary gripe with the game is that the controls are "too good".  There isn't much in the way of challenge with how fixed up the controls are.  I always had fun fighting with the steering wheel in the real Hard/Race Drivin', which if you remember, could be turned multiple times, heh.  In any case, thanks so much for humoring me on this little side quest.  Hopefully, we get this working reasonably well:)
